"""
All HTTP Status Codes as per:
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes
"""

__license__ = 'GPL-3.0+'

from enum import IntEnum

class SoupyStatus(IntEnum):
    # 1xx Informational responses
    CONTINUE = 100
    SWITCHING_PROTOCOLS = 101
    PROCESSING = 102

    # 2xx Success
    OK = 200
    CREATED = 201
    ACCEPTED = 202
    NON_AUTHORITATIVE_INFORMATION = 203
    NO_CONTENT = 204
    RESET_CONTENT = 205
    PARTIAL_CONTENT = 206
    MULTI_STATUS = 207
    ALREADY_REPORTED = 208
    IM_USED = 226

    # 3xx Redirection
    MULTIPLE_CHOICES = 300
    MOVED_PERMANENTLY = 301
    FOUND = 302
    SEE_OTHER = 303
    NOT_MODIFIED = 304
    USE_PROXY = 305
    SWITCH_PROXY = 306
    TEMPORARY_REDIRECT = 307
    PERMANENT_REDIRECT = 308

    # 4xx Client errors
    BAD_REQUEST = 400
    UNAUTHORIZED = 401
    PAYMENT_REQUIRED = 402
    FORBIDDEN = 403
    NOT_FOUND = 404
    METHOD_NOT_ALLOWED = 405
    NOT_ACCEPTABLE = 406
    PROXY_AUTHENTICATION_REQUIRED = 407
    REQUEST_TIMEOUT = 408
    CONFLICT = 409
    GONE = 410
    LENGTH_REQUIRED = 411
    PRECONDITION_FAILED = 412
    PAYLOAD_TOO_LARGE = 413
    URI_TOO_LONG = 414
    UNSUPPORTED_MEDIA_TYPE = 415
    RANGE_NOT_SATISFIABLE = 416
    EXPECTATION_FAILED = 417
    IM_A_TEAPOT = 418
    MISDIRECTED_REQUEST = 421
    UNPROCESSABLE_ENTITY = 422
    LOCKED = 423
    FAILED_DEPENDENCY = 424
    UPGRADE_REQUIRED = 426
    PRECONDITION_REQUIRED = 428
    TOO_MANY_REQUESTS = 429
    REQUEST_HEADER_FIELDS_TOO_LARGE = 431

    # 5xx Server errors
    INTERNAL_SERVER_ERROR = 500
    NOT_IMPLEMENTED = 501
    BAD_GATEWAY = 502
    SERVICE_UNAVAILABLE = 503
    GATEWAY_TIMEOUT = 504
    HTTP_VERSION_NOT_SUPPORTED = 505
    VARIANT_ALSO_NEGOTIATES = 506
    INSUFFICIENT_STORAGE = 507
    LOOP_DETECTED = 508
    NOT_EXTENDED = 510
    NETWORK_AUTHENTICATION_REQUIRED = 511

    # Unofficial codes
    BLOCKED_BY_WINDOWS_PARENTAL_CONTROLS = 450
    INVALID_TOKEN = 498
    BANDWIDTH_LIMIT_EXCEEDED = 509
    SITE_IS_FROZEN = 530
    NETWORK_READ_TIMEOUT_ERROR = 598

    # Internet Information Services
    LOGIN_TIME_OUT = 440
    RETRY_WITH = 449

    # nginx
    NO_RESPONSE = 444
    SSL_CERTIFICATE_ERROR = 495
    SSL_CERTIFICATE_REQUIRED = 496
    HTTP_REQUEST_SENT_TO_HTTPS_PORT = 497

    # Cloudflare
    WEB_SERVER_IS_DOWN = 521
    CONNECTION_TIMED_OUT = 522
    ORIGIN_IS_UNREACHABLE = 523
    A_TIMEOUT_OCCURRED = 524
    SSL_HANDSHAKE_FAILED = 525
    INVALID_SSL_CERTIFICATE = 526
    RAILGUN_ERROR = 527

    # Overlapping statuses
    # Statuses that could mean 1 of 2 things.
    CHECKPOINT_OR_EARLY_HINTS = 103
    METHOD_FAILURE_OR_ENHANCE_YOUR_CALM = 420
    UNAVAILABLE_FOR_LEGAL_REASONS_OR_REDIRECT = 451
    TOKEN_REQUIRED_OR_CLIENT_CLOSED_REQUEST = 499

    # Catch all for undocumented status codes
    UNKNOWN_STATUS_CODE = 100000
